version: '3.8'
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lmbolwmy_leave
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  app:
    build: .
    env_file:
      - .env.example
    environment:
      DB_HOST: db
    ports:
      - "3002:3002"
    depends_on:
      - db
volumes:
  db_data:
